name: Save Date to Gist

on:
  # Запускается вручную
  workflow_dispatch:

jobs:
  save_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        env:
          GIST_TOKEN: ${{ secrets.TOKEN }} # Используем секрет здесь
        uses: actions/checkout@v3
