name: Save Date to Gist

on:
  # Запускается вручную
  workflow_dispatch:

jobs:
  save_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run script to save date
        env:
          GIST_TOKEN: ${{ secrets.TOKEN }} # Используем секрет здесь
        run: node ./path/to/your/script.js
